version: '3.8'

services:
  pg:
    image: postgres:15
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE_NAME}
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
