volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14.18-alpine
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat-user
      POSTGRES_PASSWORD: chat-password
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data