// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/en7ka/chat-server/internal/service/servinterface.ChatService -o chat_service_minimock.go -n ChatServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/en7ka/chat-server/internal/models"
	"github.com/gojuno/minimock/v3"
)

// ChatServiceMock implements mm_servinterface.ChatService
type ChatServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddMemberToChat          func(ctx context.Context, member *models.ChatMember) (i1 int64, err error)
	funcAddMemberToChatOrigin    string
	inspectFuncAddMemberToChat   func(ctx context.Context, member *models.ChatMember)
	afterAddMemberToChatCounter  uint64
	beforeAddMemberToChatCounter uint64
	AddMemberToChatMock          mChatServiceMockAddMemberToChat

	funcCreateChat          func(ctx context.Context, chat *models.Chat) (cp1 *models.Chat, err error)
	funcCreateChatOrigin    string
	inspectFuncCreateChat   func(ctx context.Context, chat *models.Chat)
	afterCreateChatCounter  uint64
	beforeCreateChatCounter uint64
	CreateChatMock          mChatServiceMockCreateChat

	funcGetChatById          func(ctx context.Context, chatId int64) (cp1 *models.Chat, err error)
	funcGetChatByIdOrigin    string
	inspectFuncGetChatById   func(ctx context.Context, chatId int64)
	afterGetChatByIdCounter  uint64
	beforeGetChatByIdCounter uint64
	GetChatByIdMock          mChatServiceMockGetChatById

	funcGetChatMessages          func(ctx context.Context, chatId int64) (mpa1 []*models.Message, err error)
	funcGetChatMessagesOrigin    string
	inspectFuncGetChatMessages   func(ctx context.Context, chatId int64)
	afterGetChatMessagesCounter  uint64
	beforeGetChatMessagesCounter uint64
	GetChatMessagesMock          mChatServiceMockGetChatMessages

	funcSendMessage          func(ctx context.Context, message *models.Message) (mp1 *models.Message, err error)
	funcSendMessageOrigin    string
	inspectFuncSendMessage   func(ctx context.Context, message *models.Message)
	afterSendMessageCounter  uint64
	beforeSendMessageCounter uint64
	SendMessageMock          mChatServiceMockSendMessage
}

// NewChatServiceMock returns a mock for mm_servinterface.ChatService
func NewChatServiceMock(t minimock.Tester) *ChatServiceMock {
	m := &ChatServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMemberToChatMock = mChatServiceMockAddMemberToChat{mock: m}
	m.AddMemberToChatMock.callArgs = []*ChatServiceMockAddMemberToChatParams{}

	m.CreateChatMock = mChatServiceMockCreateChat{mock: m}
	m.CreateChatMock.callArgs = []*ChatServiceMockCreateChatParams{}

	m.GetChatByIdMock = mChatServiceMockGetChatById{mock: m}
	m.GetChatByIdMock.callArgs = []*ChatServiceMockGetChatByIdParams{}

	m.GetChatMessagesMock = mChatServiceMockGetChatMessages{mock: m}
	m.GetChatMessagesMock.callArgs = []*ChatServiceMockGetChatMessagesParams{}

	m.SendMessageMock = mChatServiceMockSendMessage{mock: m}
	m.SendMessageMock.callArgs = []*ChatServiceMockSendMessageParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mChatServiceMockAddMemberToChat struct {
	optional           bool
	mock               *ChatServiceMock
	defaultExpectation *ChatServiceMockAddMemberToChatExpectation
	expectations       []*ChatServiceMockAddMemberToChatExpectation

	callArgs []*ChatServiceMockAddMemberToChatParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ChatServiceMockAddMemberToChatExpectation specifies expectation struct of the ChatService.AddMemberToChat
type ChatServiceMockAddMemberToChatExpectation struct {
	mock               *ChatServiceMock
	params             *ChatServiceMockAddMemberToChatParams
	paramPtrs          *ChatServiceMockAddMemberToChatParamPtrs
	expectationOrigins ChatServiceMockAddMemberToChatExpectationOrigins
	results            *ChatServiceMockAddMemberToChatResults
	returnOrigin       string
	Counter            uint64
}

// ChatServiceMockAddMemberToChatParams contains parameters of the ChatService.AddMemberToChat
type ChatServiceMockAddMemberToChatParams struct {
	ctx    context.Context
	member *models.ChatMember
}

// ChatServiceMockAddMemberToChatParamPtrs contains pointers to parameters of the ChatService.AddMemberToChat
type ChatServiceMockAddMemberToChatParamPtrs struct {
	ctx    *context.Context
	member **models.ChatMember
}

// ChatServiceMockAddMemberToChatResults contains results of the ChatService.AddMemberToChat
type ChatServiceMockAddMemberToChatResults struct {
	i1  int64
	err error
}

// ChatServiceMockAddMemberToChatOrigins contains origins of expectations of the ChatService.AddMemberToChat
type ChatServiceMockAddMemberToChatExpectationOrigins struct {
	origin       string
	originCtx    string
	originMember string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) Optional() *mChatServiceMockAddMemberToChat {
	mmAddMemberToChat.optional = true
	return mmAddMemberToChat
}

// Expect sets up expected params for ChatService.AddMemberToChat
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) Expect(ctx context.Context, member *models.ChatMember) *mChatServiceMockAddMemberToChat {
	if mmAddMemberToChat.mock.funcAddMemberToChat != nil {
		mmAddMemberToChat.mock.t.Fatalf("ChatServiceMock.AddMemberToChat mock is already set by Set")
	}

	if mmAddMemberToChat.defaultExpectation == nil {
		mmAddMemberToChat.defaultExpectation = &ChatServiceMockAddMemberToChatExpectation{}
	}

	if mmAddMemberToChat.defaultExpectation.paramPtrs != nil {
		mmAddMemberToChat.mock.t.Fatalf("ChatServiceMock.AddMemberToChat mock is already set by ExpectParams functions")
	}

	mmAddMemberToChat.defaultExpectation.params = &ChatServiceMockAddMemberToChatParams{ctx, member}
	mmAddMemberToChat.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddMemberToChat.expectations {
		if minimock.Equal(e.params, mmAddMemberToChat.defaultExpectation.params) {
			mmAddMemberToChat.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddMemberToChat.defaultExpectation.params)
		}
	}

	return mmAddMemberToChat
}

// ExpectCtxParam1 sets up expected param ctx for ChatService.AddMemberToChat
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) ExpectCtxParam1(ctx context.Context) *mChatServiceMockAddMemberToChat {
	if mmAddMemberToChat.mock.funcAddMemberToChat != nil {
		mmAddMemberToChat.mock.t.Fatalf("ChatServiceMock.AddMemberToChat mock is already set by Set")
	}

	if mmAddMemberToChat.defaultExpectation == nil {
		mmAddMemberToChat.defaultExpectation = &ChatServiceMockAddMemberToChatExpectation{}
	}

	if mmAddMemberToChat.defaultExpectation.params != nil {
		mmAddMemberToChat.mock.t.Fatalf("ChatServiceMock.AddMemberToChat mock is already set by Expect")
	}

	if mmAddMemberToChat.defaultExpectation.paramPtrs == nil {
		mmAddMemberToChat.defaultExpectation.paramPtrs = &ChatServiceMockAddMemberToChatParamPtrs{}
	}
	mmAddMemberToChat.defaultExpectation.paramPtrs.ctx = &ctx
	mmAddMemberToChat.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAddMemberToChat
}

// ExpectMemberParam2 sets up expected param member for ChatService.AddMemberToChat
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) ExpectMemberParam2(member *models.ChatMember) *mChatServiceMockAddMemberToChat {
	if mmAddMemberToChat.mock.funcAddMemberToChat != nil {
		mmAddMemberToChat.mock.t.Fatalf("ChatServiceMock.AddMemberToChat mock is already set by Set")
	}

	if mmAddMemberToChat.defaultExpectation == nil {
		mmAddMemberToChat.defaultExpectation = &ChatServiceMockAddMemberToChatExpectation{}
	}

	if mmAddMemberToChat.defaultExpectation.params != nil {
		mmAddMemberToChat.mock.t.Fatalf("ChatServiceMock.AddMemberToChat mock is already set by Expect")
	}

	if mmAddMemberToChat.defaultExpectation.paramPtrs == nil {
		mmAddMemberToChat.defaultExpectation.paramPtrs = &ChatServiceMockAddMemberToChatParamPtrs{}
	}
	mmAddMemberToChat.defaultExpectation.paramPtrs.member = &member
	mmAddMemberToChat.defaultExpectation.expectationOrigins.originMember = minimock.CallerInfo(1)

	return mmAddMemberToChat
}

// Inspect accepts an inspector function that has same arguments as the ChatService.AddMemberToChat
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) Inspect(f func(ctx context.Context, member *models.ChatMember)) *mChatServiceMockAddMemberToChat {
	if mmAddMemberToChat.mock.inspectFuncAddMemberToChat != nil {
		mmAddMemberToChat.mock.t.Fatalf("Inspect function is already set for ChatServiceMock.AddMemberToChat")
	}

	mmAddMemberToChat.mock.inspectFuncAddMemberToChat = f

	return mmAddMemberToChat
}

// Return sets up results that will be returned by ChatService.AddMemberToChat
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) Return(i1 int64, err error) *ChatServiceMock {
	if mmAddMemberToChat.mock.funcAddMemberToChat != nil {
		mmAddMemberToChat.mock.t.Fatalf("ChatServiceMock.AddMemberToChat mock is already set by Set")
	}

	if mmAddMemberToChat.defaultExpectation == nil {
		mmAddMemberToChat.defaultExpectation = &ChatServiceMockAddMemberToChatExpectation{mock: mmAddMemberToChat.mock}
	}
	mmAddMemberToChat.defaultExpectation.results = &ChatServiceMockAddMemberToChatResults{i1, err}
	mmAddMemberToChat.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddMemberToChat.mock
}

// Set uses given function f to mock the ChatService.AddMemberToChat method
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) Set(f func(ctx context.Context, member *models.ChatMember) (i1 int64, err error)) *ChatServiceMock {
	if mmAddMemberToChat.defaultExpectation != nil {
		mmAddMemberToChat.mock.t.Fatalf("Default expectation is already set for the ChatService.AddMemberToChat method")
	}

	if len(mmAddMemberToChat.expectations) > 0 {
		mmAddMemberToChat.mock.t.Fatalf("Some expectations are already set for the ChatService.AddMemberToChat method")
	}

	mmAddMemberToChat.mock.funcAddMemberToChat = f
	mmAddMemberToChat.mock.funcAddMemberToChatOrigin = minimock.CallerInfo(1)
	return mmAddMemberToChat.mock
}

// When sets expectation for the ChatService.AddMemberToChat which will trigger the result defined by the following
// Then helper
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) When(ctx context.Context, member *models.ChatMember) *ChatServiceMockAddMemberToChatExpectation {
	if mmAddMemberToChat.mock.funcAddMemberToChat != nil {
		mmAddMemberToChat.mock.t.Fatalf("ChatServiceMock.AddMemberToChat mock is already set by Set")
	}

	expectation := &ChatServiceMockAddMemberToChatExpectation{
		mock:               mmAddMemberToChat.mock,
		params:             &ChatServiceMockAddMemberToChatParams{ctx, member},
		expectationOrigins: ChatServiceMockAddMemberToChatExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddMemberToChat.expectations = append(mmAddMemberToChat.expectations, expectation)
	return expectation
}

// Then sets up ChatService.AddMemberToChat return parameters for the expectation previously defined by the When method
func (e *ChatServiceMockAddMemberToChatExpectation) Then(i1 int64, err error) *ChatServiceMock {
	e.results = &ChatServiceMockAddMemberToChatResults{i1, err}
	return e.mock
}

// Times sets number of times ChatService.AddMemberToChat should be invoked
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) Times(n uint64) *mChatServiceMockAddMemberToChat {
	if n == 0 {
		mmAddMemberToChat.mock.t.Fatalf("Times of ChatServiceMock.AddMemberToChat mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddMemberToChat.expectedInvocations, n)
	mmAddMemberToChat.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddMemberToChat
}

func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) invocationsDone() bool {
	if len(mmAddMemberToChat.expectations) == 0 && mmAddMemberToChat.defaultExpectation == nil && mmAddMemberToChat.mock.funcAddMemberToChat == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddMemberToChat.mock.afterAddMemberToChatCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddMemberToChat.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddMemberToChat implements mm_servinterface.ChatService
func (mmAddMemberToChat *ChatServiceMock) AddMemberToChat(ctx context.Context, member *models.ChatMember) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmAddMemberToChat.beforeAddMemberToChatCounter, 1)
	defer mm_atomic.AddUint64(&mmAddMemberToChat.afterAddMemberToChatCounter, 1)

	mmAddMemberToChat.t.Helper()

	if mmAddMemberToChat.inspectFuncAddMemberToChat != nil {
		mmAddMemberToChat.inspectFuncAddMemberToChat(ctx, member)
	}

	mm_params := ChatServiceMockAddMemberToChatParams{ctx, member}

	// Record call args
	mmAddMemberToChat.AddMemberToChatMock.mutex.Lock()
	mmAddMemberToChat.AddMemberToChatMock.callArgs = append(mmAddMemberToChat.AddMemberToChatMock.callArgs, &mm_params)
	mmAddMemberToChat.AddMemberToChatMock.mutex.Unlock()

	for _, e := range mmAddMemberToChat.AddMemberToChatMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmAddMemberToChat.AddMemberToChatMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddMemberToChat.AddMemberToChatMock.defaultExpectation.Counter, 1)
		mm_want := mmAddMemberToChat.AddMemberToChatMock.defaultExpectation.params
		mm_want_ptrs := mmAddMemberToChat.AddMemberToChatMock.defaultExpectation.paramPtrs

		mm_got := ChatServiceMockAddMemberToChatParams{ctx, member}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAddMemberToChat.t.Errorf("ChatServiceMock.AddMemberToChat got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddMemberToChat.AddMemberToChatMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.member != nil && !minimock.Equal(*mm_want_ptrs.member, mm_got.member) {
				mmAddMemberToChat.t.Errorf("ChatServiceMock.AddMemberToChat got unexpected parameter member, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddMemberToChat.AddMemberToChatMock.defaultExpectation.expectationOrigins.originMember, *mm_want_ptrs.member, mm_got.member, minimock.Diff(*mm_want_ptrs.member, mm_got.member))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddMemberToChat.t.Errorf("ChatServiceMock.AddMemberToChat got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddMemberToChat.AddMemberToChatMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddMemberToChat.AddMemberToChatMock.defaultExpectation.results
		if mm_results == nil {
			mmAddMemberToChat.t.Fatal("No results are set for the ChatServiceMock.AddMemberToChat")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmAddMemberToChat.funcAddMemberToChat != nil {
		return mmAddMemberToChat.funcAddMemberToChat(ctx, member)
	}
	mmAddMemberToChat.t.Fatalf("Unexpected call to ChatServiceMock.AddMemberToChat. %v %v", ctx, member)
	return
}

// AddMemberToChatAfterCounter returns a count of finished ChatServiceMock.AddMemberToChat invocations
func (mmAddMemberToChat *ChatServiceMock) AddMemberToChatAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddMemberToChat.afterAddMemberToChatCounter)
}

// AddMemberToChatBeforeCounter returns a count of ChatServiceMock.AddMemberToChat invocations
func (mmAddMemberToChat *ChatServiceMock) AddMemberToChatBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddMemberToChat.beforeAddMemberToChatCounter)
}

// Calls returns a list of arguments used in each call to ChatServiceMock.AddMemberToChat.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddMemberToChat *mChatServiceMockAddMemberToChat) Calls() []*ChatServiceMockAddMemberToChatParams {
	mmAddMemberToChat.mutex.RLock()

	argCopy := make([]*ChatServiceMockAddMemberToChatParams, len(mmAddMemberToChat.callArgs))
	copy(argCopy, mmAddMemberToChat.callArgs)

	mmAddMemberToChat.mutex.RUnlock()

	return argCopy
}

// MinimockAddMemberToChatDone returns true if the count of the AddMemberToChat invocations corresponds
// the number of defined expectations
func (m *ChatServiceMock) MinimockAddMemberToChatDone() bool {
	if m.AddMemberToChatMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddMemberToChatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddMemberToChatMock.invocationsDone()
}

// MinimockAddMemberToChatInspect logs each unmet expectation
func (m *ChatServiceMock) MinimockAddMemberToChatInspect() {
	for _, e := range m.AddMemberToChatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ChatServiceMock.AddMemberToChat at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddMemberToChatCounter := mm_atomic.LoadUint64(&m.afterAddMemberToChatCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddMemberToChatMock.defaultExpectation != nil && afterAddMemberToChatCounter < 1 {
		if m.AddMemberToChatMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ChatServiceMock.AddMemberToChat at\n%s", m.AddMemberToChatMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ChatServiceMock.AddMemberToChat at\n%s with params: %#v", m.AddMemberToChatMock.defaultExpectation.expectationOrigins.origin, *m.AddMemberToChatMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddMemberToChat != nil && afterAddMemberToChatCounter < 1 {
		m.t.Errorf("Expected call to ChatServiceMock.AddMemberToChat at\n%s", m.funcAddMemberToChatOrigin)
	}

	if !m.AddMemberToChatMock.invocationsDone() && afterAddMemberToChatCounter > 0 {
		m.t.Errorf("Expected %d calls to ChatServiceMock.AddMemberToChat at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddMemberToChatMock.expectedInvocations), m.AddMemberToChatMock.expectedInvocationsOrigin, afterAddMemberToChatCounter)
	}
}

type mChatServiceMockCreateChat struct {
	optional           bool
	mock               *ChatServiceMock
	defaultExpectation *ChatServiceMockCreateChatExpectation
	expectations       []*ChatServiceMockCreateChatExpectation

	callArgs []*ChatServiceMockCreateChatParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ChatServiceMockCreateChatExpectation specifies expectation struct of the ChatService.CreateChat
type ChatServiceMockCreateChatExpectation struct {
	mock               *ChatServiceMock
	params             *ChatServiceMockCreateChatParams
	paramPtrs          *ChatServiceMockCreateChatParamPtrs
	expectationOrigins ChatServiceMockCreateChatExpectationOrigins
	results            *ChatServiceMockCreateChatResults
	returnOrigin       string
	Counter            uint64
}

// ChatServiceMockCreateChatParams contains parameters of the ChatService.CreateChat
type ChatServiceMockCreateChatParams struct {
	ctx  context.Context
	chat *models.Chat
}

// ChatServiceMockCreateChatParamPtrs contains pointers to parameters of the ChatService.CreateChat
type ChatServiceMockCreateChatParamPtrs struct {
	ctx  *context.Context
	chat **models.Chat
}

// ChatServiceMockCreateChatResults contains results of the ChatService.CreateChat
type ChatServiceMockCreateChatResults struct {
	cp1 *models.Chat
	err error
}

// ChatServiceMockCreateChatOrigins contains origins of expectations of the ChatService.CreateChat
type ChatServiceMockCreateChatExpectationOrigins struct {
	origin     string
	originCtx  string
	originChat string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateChat *mChatServiceMockCreateChat) Optional() *mChatServiceMockCreateChat {
	mmCreateChat.optional = true
	return mmCreateChat
}

// Expect sets up expected params for ChatService.CreateChat
func (mmCreateChat *mChatServiceMockCreateChat) Expect(ctx context.Context, chat *models.Chat) *mChatServiceMockCreateChat {
	if mmCreateChat.mock.funcCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("ChatServiceMock.CreateChat mock is already set by Set")
	}

	if mmCreateChat.defaultExpectation == nil {
		mmCreateChat.defaultExpectation = &ChatServiceMockCreateChatExpectation{}
	}

	if mmCreateChat.defaultExpectation.paramPtrs != nil {
		mmCreateChat.mock.t.Fatalf("ChatServiceMock.CreateChat mock is already set by ExpectParams functions")
	}

	mmCreateChat.defaultExpectation.params = &ChatServiceMockCreateChatParams{ctx, chat}
	mmCreateChat.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateChat.expectations {
		if minimock.Equal(e.params, mmCreateChat.defaultExpectation.params) {
			mmCreateChat.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateChat.defaultExpectation.params)
		}
	}

	return mmCreateChat
}

// ExpectCtxParam1 sets up expected param ctx for ChatService.CreateChat
func (mmCreateChat *mChatServiceMockCreateChat) ExpectCtxParam1(ctx context.Context) *mChatServiceMockCreateChat {
	if mmCreateChat.mock.funcCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("ChatServiceMock.CreateChat mock is already set by Set")
	}

	if mmCreateChat.defaultExpectation == nil {
		mmCreateChat.defaultExpectation = &ChatServiceMockCreateChatExpectation{}
	}

	if mmCreateChat.defaultExpectation.params != nil {
		mmCreateChat.mock.t.Fatalf("ChatServiceMock.CreateChat mock is already set by Expect")
	}

	if mmCreateChat.defaultExpectation.paramPtrs == nil {
		mmCreateChat.defaultExpectation.paramPtrs = &ChatServiceMockCreateChatParamPtrs{}
	}
	mmCreateChat.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateChat.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateChat
}

// ExpectChatParam2 sets up expected param chat for ChatService.CreateChat
func (mmCreateChat *mChatServiceMockCreateChat) ExpectChatParam2(chat *models.Chat) *mChatServiceMockCreateChat {
	if mmCreateChat.mock.funcCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("ChatServiceMock.CreateChat mock is already set by Set")
	}

	if mmCreateChat.defaultExpectation == nil {
		mmCreateChat.defaultExpectation = &ChatServiceMockCreateChatExpectation{}
	}

	if mmCreateChat.defaultExpectation.params != nil {
		mmCreateChat.mock.t.Fatalf("ChatServiceMock.CreateChat mock is already set by Expect")
	}

	if mmCreateChat.defaultExpectation.paramPtrs == nil {
		mmCreateChat.defaultExpectation.paramPtrs = &ChatServiceMockCreateChatParamPtrs{}
	}
	mmCreateChat.defaultExpectation.paramPtrs.chat = &chat
	mmCreateChat.defaultExpectation.expectationOrigins.originChat = minimock.CallerInfo(1)

	return mmCreateChat
}

// Inspect accepts an inspector function that has same arguments as the ChatService.CreateChat
func (mmCreateChat *mChatServiceMockCreateChat) Inspect(f func(ctx context.Context, chat *models.Chat)) *mChatServiceMockCreateChat {
	if mmCreateChat.mock.inspectFuncCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("Inspect function is already set for ChatServiceMock.CreateChat")
	}

	mmCreateChat.mock.inspectFuncCreateChat = f

	return mmCreateChat
}

// Return sets up results that will be returned by ChatService.CreateChat
func (mmCreateChat *mChatServiceMockCreateChat) Return(cp1 *models.Chat, err error) *ChatServiceMock {
	if mmCreateChat.mock.funcCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("ChatServiceMock.CreateChat mock is already set by Set")
	}

	if mmCreateChat.defaultExpectation == nil {
		mmCreateChat.defaultExpectation = &ChatServiceMockCreateChatExpectation{mock: mmCreateChat.mock}
	}
	mmCreateChat.defaultExpectation.results = &ChatServiceMockCreateChatResults{cp1, err}
	mmCreateChat.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateChat.mock
}

// Set uses given function f to mock the ChatService.CreateChat method
func (mmCreateChat *mChatServiceMockCreateChat) Set(f func(ctx context.Context, chat *models.Chat) (cp1 *models.Chat, err error)) *ChatServiceMock {
	if mmCreateChat.defaultExpectation != nil {
		mmCreateChat.mock.t.Fatalf("Default expectation is already set for the ChatService.CreateChat method")
	}

	if len(mmCreateChat.expectations) > 0 {
		mmCreateChat.mock.t.Fatalf("Some expectations are already set for the ChatService.CreateChat method")
	}

	mmCreateChat.mock.funcCreateChat = f
	mmCreateChat.mock.funcCreateChatOrigin = minimock.CallerInfo(1)
	return mmCreateChat.mock
}

// When sets expectation for the ChatService.CreateChat which will trigger the result defined by the following
// Then helper
func (mmCreateChat *mChatServiceMockCreateChat) When(ctx context.Context, chat *models.Chat) *ChatServiceMockCreateChatExpectation {
	if mmCreateChat.mock.funcCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("ChatServiceMock.CreateChat mock is already set by Set")
	}

	expectation := &ChatServiceMockCreateChatExpectation{
		mock:               mmCreateChat.mock,
		params:             &ChatServiceMockCreateChatParams{ctx, chat},
		expectationOrigins: ChatServiceMockCreateChatExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateChat.expectations = append(mmCreateChat.expectations, expectation)
	return expectation
}

// Then sets up ChatService.CreateChat return parameters for the expectation previously defined by the When method
func (e *ChatServiceMockCreateChatExpectation) Then(cp1 *models.Chat, err error) *ChatServiceMock {
	e.results = &ChatServiceMockCreateChatResults{cp1, err}
	return e.mock
}

// Times sets number of times ChatService.CreateChat should be invoked
func (mmCreateChat *mChatServiceMockCreateChat) Times(n uint64) *mChatServiceMockCreateChat {
	if n == 0 {
		mmCreateChat.mock.t.Fatalf("Times of ChatServiceMock.CreateChat mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateChat.expectedInvocations, n)
	mmCreateChat.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateChat
}

func (mmCreateChat *mChatServiceMockCreateChat) invocationsDone() bool {
	if len(mmCreateChat.expectations) == 0 && mmCreateChat.defaultExpectation == nil && mmCreateChat.mock.funcCreateChat == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateChat.mock.afterCreateChatCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateChat.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateChat implements mm_servinterface.ChatService
func (mmCreateChat *ChatServiceMock) CreateChat(ctx context.Context, chat *models.Chat) (cp1 *models.Chat, err error) {
	mm_atomic.AddUint64(&mmCreateChat.beforeCreateChatCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateChat.afterCreateChatCounter, 1)

	mmCreateChat.t.Helper()

	if mmCreateChat.inspectFuncCreateChat != nil {
		mmCreateChat.inspectFuncCreateChat(ctx, chat)
	}

	mm_params := ChatServiceMockCreateChatParams{ctx, chat}

	// Record call args
	mmCreateChat.CreateChatMock.mutex.Lock()
	mmCreateChat.CreateChatMock.callArgs = append(mmCreateChat.CreateChatMock.callArgs, &mm_params)
	mmCreateChat.CreateChatMock.mutex.Unlock()

	for _, e := range mmCreateChat.CreateChatMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmCreateChat.CreateChatMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateChat.CreateChatMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateChat.CreateChatMock.defaultExpectation.params
		mm_want_ptrs := mmCreateChat.CreateChatMock.defaultExpectation.paramPtrs

		mm_got := ChatServiceMockCreateChatParams{ctx, chat}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateChat.t.Errorf("ChatServiceMock.CreateChat got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateChat.CreateChatMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.chat != nil && !minimock.Equal(*mm_want_ptrs.chat, mm_got.chat) {
				mmCreateChat.t.Errorf("ChatServiceMock.CreateChat got unexpected parameter chat, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateChat.CreateChatMock.defaultExpectation.expectationOrigins.originChat, *mm_want_ptrs.chat, mm_got.chat, minimock.Diff(*mm_want_ptrs.chat, mm_got.chat))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateChat.t.Errorf("ChatServiceMock.CreateChat got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateChat.CreateChatMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateChat.CreateChatMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateChat.t.Fatal("No results are set for the ChatServiceMock.CreateChat")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmCreateChat.funcCreateChat != nil {
		return mmCreateChat.funcCreateChat(ctx, chat)
	}
	mmCreateChat.t.Fatalf("Unexpected call to ChatServiceMock.CreateChat. %v %v", ctx, chat)
	return
}

// CreateChatAfterCounter returns a count of finished ChatServiceMock.CreateChat invocations
func (mmCreateChat *ChatServiceMock) CreateChatAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateChat.afterCreateChatCounter)
}

// CreateChatBeforeCounter returns a count of ChatServiceMock.CreateChat invocations
func (mmCreateChat *ChatServiceMock) CreateChatBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateChat.beforeCreateChatCounter)
}

// Calls returns a list of arguments used in each call to ChatServiceMock.CreateChat.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateChat *mChatServiceMockCreateChat) Calls() []*ChatServiceMockCreateChatParams {
	mmCreateChat.mutex.RLock()

	argCopy := make([]*ChatServiceMockCreateChatParams, len(mmCreateChat.callArgs))
	copy(argCopy, mmCreateChat.callArgs)

	mmCreateChat.mutex.RUnlock()

	return argCopy
}

// MinimockCreateChatDone returns true if the count of the CreateChat invocations corresponds
// the number of defined expectations
func (m *ChatServiceMock) MinimockCreateChatDone() bool {
	if m.CreateChatMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateChatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateChatMock.invocationsDone()
}

// MinimockCreateChatInspect logs each unmet expectation
func (m *ChatServiceMock) MinimockCreateChatInspect() {
	for _, e := range m.CreateChatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ChatServiceMock.CreateChat at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateChatCounter := mm_atomic.LoadUint64(&m.afterCreateChatCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateChatMock.defaultExpectation != nil && afterCreateChatCounter < 1 {
		if m.CreateChatMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ChatServiceMock.CreateChat at\n%s", m.CreateChatMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ChatServiceMock.CreateChat at\n%s with params: %#v", m.CreateChatMock.defaultExpectation.expectationOrigins.origin, *m.CreateChatMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateChat != nil && afterCreateChatCounter < 1 {
		m.t.Errorf("Expected call to ChatServiceMock.CreateChat at\n%s", m.funcCreateChatOrigin)
	}

	if !m.CreateChatMock.invocationsDone() && afterCreateChatCounter > 0 {
		m.t.Errorf("Expected %d calls to ChatServiceMock.CreateChat at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateChatMock.expectedInvocations), m.CreateChatMock.expectedInvocationsOrigin, afterCreateChatCounter)
	}
}

type mChatServiceMockGetChatById struct {
	optional           bool
	mock               *ChatServiceMock
	defaultExpectation *ChatServiceMockGetChatByIdExpectation
	expectations       []*ChatServiceMockGetChatByIdExpectation

	callArgs []*ChatServiceMockGetChatByIdParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ChatServiceMockGetChatByIdExpectation specifies expectation struct of the ChatService.GetChatById
type ChatServiceMockGetChatByIdExpectation struct {
	mock               *ChatServiceMock
	params             *ChatServiceMockGetChatByIdParams
	paramPtrs          *ChatServiceMockGetChatByIdParamPtrs
	expectationOrigins ChatServiceMockGetChatByIdExpectationOrigins
	results            *ChatServiceMockGetChatByIdResults
	returnOrigin       string
	Counter            uint64
}

// ChatServiceMockGetChatByIdParams contains parameters of the ChatService.GetChatById
type ChatServiceMockGetChatByIdParams struct {
	ctx    context.Context
	chatId int64
}

// ChatServiceMockGetChatByIdParamPtrs contains pointers to parameters of the ChatService.GetChatById
type ChatServiceMockGetChatByIdParamPtrs struct {
	ctx    *context.Context
	chatId *int64
}

// ChatServiceMockGetChatByIdResults contains results of the ChatService.GetChatById
type ChatServiceMockGetChatByIdResults struct {
	cp1 *models.Chat
	err error
}

// ChatServiceMockGetChatByIdOrigins contains origins of expectations of the ChatService.GetChatById
type ChatServiceMockGetChatByIdExpectationOrigins struct {
	origin       string
	originCtx    string
	originChatId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetChatById *mChatServiceMockGetChatById) Optional() *mChatServiceMockGetChatById {
	mmGetChatById.optional = true
	return mmGetChatById
}

// Expect sets up expected params for ChatService.GetChatById
func (mmGetChatById *mChatServiceMockGetChatById) Expect(ctx context.Context, chatId int64) *mChatServiceMockGetChatById {
	if mmGetChatById.mock.funcGetChatById != nil {
		mmGetChatById.mock.t.Fatalf("ChatServiceMock.GetChatById mock is already set by Set")
	}

	if mmGetChatById.defaultExpectation == nil {
		mmGetChatById.defaultExpectation = &ChatServiceMockGetChatByIdExpectation{}
	}

	if mmGetChatById.defaultExpectation.paramPtrs != nil {
		mmGetChatById.mock.t.Fatalf("ChatServiceMock.GetChatById mock is already set by ExpectParams functions")
	}

	mmGetChatById.defaultExpectation.params = &ChatServiceMockGetChatByIdParams{ctx, chatId}
	mmGetChatById.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetChatById.expectations {
		if minimock.Equal(e.params, mmGetChatById.defaultExpectation.params) {
			mmGetChatById.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetChatById.defaultExpectation.params)
		}
	}

	return mmGetChatById
}

// ExpectCtxParam1 sets up expected param ctx for ChatService.GetChatById
func (mmGetChatById *mChatServiceMockGetChatById) ExpectCtxParam1(ctx context.Context) *mChatServiceMockGetChatById {
	if mmGetChatById.mock.funcGetChatById != nil {
		mmGetChatById.mock.t.Fatalf("ChatServiceMock.GetChatById mock is already set by Set")
	}

	if mmGetChatById.defaultExpectation == nil {
		mmGetChatById.defaultExpectation = &ChatServiceMockGetChatByIdExpectation{}
	}

	if mmGetChatById.defaultExpectation.params != nil {
		mmGetChatById.mock.t.Fatalf("ChatServiceMock.GetChatById mock is already set by Expect")
	}

	if mmGetChatById.defaultExpectation.paramPtrs == nil {
		mmGetChatById.defaultExpectation.paramPtrs = &ChatServiceMockGetChatByIdParamPtrs{}
	}
	mmGetChatById.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetChatById.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetChatById
}

// ExpectChatIdParam2 sets up expected param chatId for ChatService.GetChatById
func (mmGetChatById *mChatServiceMockGetChatById) ExpectChatIdParam2(chatId int64) *mChatServiceMockGetChatById {
	if mmGetChatById.mock.funcGetChatById != nil {
		mmGetChatById.mock.t.Fatalf("ChatServiceMock.GetChatById mock is already set by Set")
	}

	if mmGetChatById.defaultExpectation == nil {
		mmGetChatById.defaultExpectation = &ChatServiceMockGetChatByIdExpectation{}
	}

	if mmGetChatById.defaultExpectation.params != nil {
		mmGetChatById.mock.t.Fatalf("ChatServiceMock.GetChatById mock is already set by Expect")
	}

	if mmGetChatById.defaultExpectation.paramPtrs == nil {
		mmGetChatById.defaultExpectation.paramPtrs = &ChatServiceMockGetChatByIdParamPtrs{}
	}
	mmGetChatById.defaultExpectation.paramPtrs.chatId = &chatId
	mmGetChatById.defaultExpectation.expectationOrigins.originChatId = minimock.CallerInfo(1)

	return mmGetChatById
}

// Inspect accepts an inspector function that has same arguments as the ChatService.GetChatById
func (mmGetChatById *mChatServiceMockGetChatById) Inspect(f func(ctx context.Context, chatId int64)) *mChatServiceMockGetChatById {
	if mmGetChatById.mock.inspectFuncGetChatById != nil {
		mmGetChatById.mock.t.Fatalf("Inspect function is already set for ChatServiceMock.GetChatById")
	}

	mmGetChatById.mock.inspectFuncGetChatById = f

	return mmGetChatById
}

// Return sets up results that will be returned by ChatService.GetChatById
func (mmGetChatById *mChatServiceMockGetChatById) Return(cp1 *models.Chat, err error) *ChatServiceMock {
	if mmGetChatById.mock.funcGetChatById != nil {
		mmGetChatById.mock.t.Fatalf("ChatServiceMock.GetChatById mock is already set by Set")
	}

	if mmGetChatById.defaultExpectation == nil {
		mmGetChatById.defaultExpectation = &ChatServiceMockGetChatByIdExpectation{mock: mmGetChatById.mock}
	}
	mmGetChatById.defaultExpectation.results = &ChatServiceMockGetChatByIdResults{cp1, err}
	mmGetChatById.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetChatById.mock
}

// Set uses given function f to mock the ChatService.GetChatById method
func (mmGetChatById *mChatServiceMockGetChatById) Set(f func(ctx context.Context, chatId int64) (cp1 *models.Chat, err error)) *ChatServiceMock {
	if mmGetChatById.defaultExpectation != nil {
		mmGetChatById.mock.t.Fatalf("Default expectation is already set for the ChatService.GetChatById method")
	}

	if len(mmGetChatById.expectations) > 0 {
		mmGetChatById.mock.t.Fatalf("Some expectations are already set for the ChatService.GetChatById method")
	}

	mmGetChatById.mock.funcGetChatById = f
	mmGetChatById.mock.funcGetChatByIdOrigin = minimock.CallerInfo(1)
	return mmGetChatById.mock
}

// When sets expectation for the ChatService.GetChatById which will trigger the result defined by the following
// Then helper
func (mmGetChatById *mChatServiceMockGetChatById) When(ctx context.Context, chatId int64) *ChatServiceMockGetChatByIdExpectation {
	if mmGetChatById.mock.funcGetChatById != nil {
		mmGetChatById.mock.t.Fatalf("ChatServiceMock.GetChatById mock is already set by Set")
	}

	expectation := &ChatServiceMockGetChatByIdExpectation{
		mock:               mmGetChatById.mock,
		params:             &ChatServiceMockGetChatByIdParams{ctx, chatId},
		expectationOrigins: ChatServiceMockGetChatByIdExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetChatById.expectations = append(mmGetChatById.expectations, expectation)
	return expectation
}

// Then sets up ChatService.GetChatById return parameters for the expectation previously defined by the When method
func (e *ChatServiceMockGetChatByIdExpectation) Then(cp1 *models.Chat, err error) *ChatServiceMock {
	e.results = &ChatServiceMockGetChatByIdResults{cp1, err}
	return e.mock
}

// Times sets number of times ChatService.GetChatById should be invoked
func (mmGetChatById *mChatServiceMockGetChatById) Times(n uint64) *mChatServiceMockGetChatById {
	if n == 0 {
		mmGetChatById.mock.t.Fatalf("Times of ChatServiceMock.GetChatById mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetChatById.expectedInvocations, n)
	mmGetChatById.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetChatById
}

func (mmGetChatById *mChatServiceMockGetChatById) invocationsDone() bool {
	if len(mmGetChatById.expectations) == 0 && mmGetChatById.defaultExpectation == nil && mmGetChatById.mock.funcGetChatById == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetChatById.mock.afterGetChatByIdCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetChatById.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetChatById implements mm_servinterface.ChatService
func (mmGetChatById *ChatServiceMock) GetChatById(ctx context.Context, chatId int64) (cp1 *models.Chat, err error) {
	mm_atomic.AddUint64(&mmGetChatById.beforeGetChatByIdCounter, 1)
	defer mm_atomic.AddUint64(&mmGetChatById.afterGetChatByIdCounter, 1)

	mmGetChatById.t.Helper()

	if mmGetChatById.inspectFuncGetChatById != nil {
		mmGetChatById.inspectFuncGetChatById(ctx, chatId)
	}

	mm_params := ChatServiceMockGetChatByIdParams{ctx, chatId}

	// Record call args
	mmGetChatById.GetChatByIdMock.mutex.Lock()
	mmGetChatById.GetChatByIdMock.callArgs = append(mmGetChatById.GetChatByIdMock.callArgs, &mm_params)
	mmGetChatById.GetChatByIdMock.mutex.Unlock()

	for _, e := range mmGetChatById.GetChatByIdMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmGetChatById.GetChatByIdMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetChatById.GetChatByIdMock.defaultExpectation.Counter, 1)
		mm_want := mmGetChatById.GetChatByIdMock.defaultExpectation.params
		mm_want_ptrs := mmGetChatById.GetChatByIdMock.defaultExpectation.paramPtrs

		mm_got := ChatServiceMockGetChatByIdParams{ctx, chatId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetChatById.t.Errorf("ChatServiceMock.GetChatById got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetChatById.GetChatByIdMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.chatId != nil && !minimock.Equal(*mm_want_ptrs.chatId, mm_got.chatId) {
				mmGetChatById.t.Errorf("ChatServiceMock.GetChatById got unexpected parameter chatId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetChatById.GetChatByIdMock.defaultExpectation.expectationOrigins.originChatId, *mm_want_ptrs.chatId, mm_got.chatId, minimock.Diff(*mm_want_ptrs.chatId, mm_got.chatId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetChatById.t.Errorf("ChatServiceMock.GetChatById got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetChatById.GetChatByIdMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetChatById.GetChatByIdMock.defaultExpectation.results
		if mm_results == nil {
			mmGetChatById.t.Fatal("No results are set for the ChatServiceMock.GetChatById")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmGetChatById.funcGetChatById != nil {
		return mmGetChatById.funcGetChatById(ctx, chatId)
	}
	mmGetChatById.t.Fatalf("Unexpected call to ChatServiceMock.GetChatById. %v %v", ctx, chatId)
	return
}

// GetChatByIdAfterCounter returns a count of finished ChatServiceMock.GetChatById invocations
func (mmGetChatById *ChatServiceMock) GetChatByIdAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetChatById.afterGetChatByIdCounter)
}

// GetChatByIdBeforeCounter returns a count of ChatServiceMock.GetChatById invocations
func (mmGetChatById *ChatServiceMock) GetChatByIdBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetChatById.beforeGetChatByIdCounter)
}

// Calls returns a list of arguments used in each call to ChatServiceMock.GetChatById.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetChatById *mChatServiceMockGetChatById) Calls() []*ChatServiceMockGetChatByIdParams {
	mmGetChatById.mutex.RLock()

	argCopy := make([]*ChatServiceMockGetChatByIdParams, len(mmGetChatById.callArgs))
	copy(argCopy, mmGetChatById.callArgs)

	mmGetChatById.mutex.RUnlock()

	return argCopy
}

// MinimockGetChatByIdDone returns true if the count of the GetChatById invocations corresponds
// the number of defined expectations
func (m *ChatServiceMock) MinimockGetChatByIdDone() bool {
	if m.GetChatByIdMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetChatByIdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetChatByIdMock.invocationsDone()
}

// MinimockGetChatByIdInspect logs each unmet expectation
func (m *ChatServiceMock) MinimockGetChatByIdInspect() {
	for _, e := range m.GetChatByIdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ChatServiceMock.GetChatById at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetChatByIdCounter := mm_atomic.LoadUint64(&m.afterGetChatByIdCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetChatByIdMock.defaultExpectation != nil && afterGetChatByIdCounter < 1 {
		if m.GetChatByIdMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ChatServiceMock.GetChatById at\n%s", m.GetChatByIdMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ChatServiceMock.GetChatById at\n%s with params: %#v", m.GetChatByIdMock.defaultExpectation.expectationOrigins.origin, *m.GetChatByIdMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetChatById != nil && afterGetChatByIdCounter < 1 {
		m.t.Errorf("Expected call to ChatServiceMock.GetChatById at\n%s", m.funcGetChatByIdOrigin)
	}

	if !m.GetChatByIdMock.invocationsDone() && afterGetChatByIdCounter > 0 {
		m.t.Errorf("Expected %d calls to ChatServiceMock.GetChatById at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetChatByIdMock.expectedInvocations), m.GetChatByIdMock.expectedInvocationsOrigin, afterGetChatByIdCounter)
	}
}

type mChatServiceMockGetChatMessages struct {
	optional           bool
	mock               *ChatServiceMock
	defaultExpectation *ChatServiceMockGetChatMessagesExpectation
	expectations       []*ChatServiceMockGetChatMessagesExpectation

	callArgs []*ChatServiceMockGetChatMessagesParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ChatServiceMockGetChatMessagesExpectation specifies expectation struct of the ChatService.GetChatMessages
type ChatServiceMockGetChatMessagesExpectation struct {
	mock               *ChatServiceMock
	params             *ChatServiceMockGetChatMessagesParams
	paramPtrs          *ChatServiceMockGetChatMessagesParamPtrs
	expectationOrigins ChatServiceMockGetChatMessagesExpectationOrigins
	results            *ChatServiceMockGetChatMessagesResults
	returnOrigin       string
	Counter            uint64
}

// ChatServiceMockGetChatMessagesParams contains parameters of the ChatService.GetChatMessages
type ChatServiceMockGetChatMessagesParams struct {
	ctx    context.Context
	chatId int64
}

// ChatServiceMockGetChatMessagesParamPtrs contains pointers to parameters of the ChatService.GetChatMessages
type ChatServiceMockGetChatMessagesParamPtrs struct {
	ctx    *context.Context
	chatId *int64
}

// ChatServiceMockGetChatMessagesResults contains results of the ChatService.GetChatMessages
type ChatServiceMockGetChatMessagesResults struct {
	mpa1 []*models.Message
	err  error
}

// ChatServiceMockGetChatMessagesOrigins contains origins of expectations of the ChatService.GetChatMessages
type ChatServiceMockGetChatMessagesExpectationOrigins struct {
	origin       string
	originCtx    string
	originChatId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetChatMessages *mChatServiceMockGetChatMessages) Optional() *mChatServiceMockGetChatMessages {
	mmGetChatMessages.optional = true
	return mmGetChatMessages
}

// Expect sets up expected params for ChatService.GetChatMessages
func (mmGetChatMessages *mChatServiceMockGetChatMessages) Expect(ctx context.Context, chatId int64) *mChatServiceMockGetChatMessages {
	if mmGetChatMessages.mock.funcGetChatMessages != nil {
		mmGetChatMessages.mock.t.Fatalf("ChatServiceMock.GetChatMessages mock is already set by Set")
	}

	if mmGetChatMessages.defaultExpectation == nil {
		mmGetChatMessages.defaultExpectation = &ChatServiceMockGetChatMessagesExpectation{}
	}

	if mmGetChatMessages.defaultExpectation.paramPtrs != nil {
		mmGetChatMessages.mock.t.Fatalf("ChatServiceMock.GetChatMessages mock is already set by ExpectParams functions")
	}

	mmGetChatMessages.defaultExpectation.params = &ChatServiceMockGetChatMessagesParams{ctx, chatId}
	mmGetChatMessages.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetChatMessages.expectations {
		if minimock.Equal(e.params, mmGetChatMessages.defaultExpectation.params) {
			mmGetChatMessages.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetChatMessages.defaultExpectation.params)
		}
	}

	return mmGetChatMessages
}

// ExpectCtxParam1 sets up expected param ctx for ChatService.GetChatMessages
func (mmGetChatMessages *mChatServiceMockGetChatMessages) ExpectCtxParam1(ctx context.Context) *mChatServiceMockGetChatMessages {
	if mmGetChatMessages.mock.funcGetChatMessages != nil {
		mmGetChatMessages.mock.t.Fatalf("ChatServiceMock.GetChatMessages mock is already set by Set")
	}

	if mmGetChatMessages.defaultExpectation == nil {
		mmGetChatMessages.defaultExpectation = &ChatServiceMockGetChatMessagesExpectation{}
	}

	if mmGetChatMessages.defaultExpectation.params != nil {
		mmGetChatMessages.mock.t.Fatalf("ChatServiceMock.GetChatMessages mock is already set by Expect")
	}

	if mmGetChatMessages.defaultExpectation.paramPtrs == nil {
		mmGetChatMessages.defaultExpectation.paramPtrs = &ChatServiceMockGetChatMessagesParamPtrs{}
	}
	mmGetChatMessages.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetChatMessages.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetChatMessages
}

// ExpectChatIdParam2 sets up expected param chatId for ChatService.GetChatMessages
func (mmGetChatMessages *mChatServiceMockGetChatMessages) ExpectChatIdParam2(chatId int64) *mChatServiceMockGetChatMessages {
	if mmGetChatMessages.mock.funcGetChatMessages != nil {
		mmGetChatMessages.mock.t.Fatalf("ChatServiceMock.GetChatMessages mock is already set by Set")
	}

	if mmGetChatMessages.defaultExpectation == nil {
		mmGetChatMessages.defaultExpectation = &ChatServiceMockGetChatMessagesExpectation{}
	}

	if mmGetChatMessages.defaultExpectation.params != nil {
		mmGetChatMessages.mock.t.Fatalf("ChatServiceMock.GetChatMessages mock is already set by Expect")
	}

	if mmGetChatMessages.defaultExpectation.paramPtrs == nil {
		mmGetChatMessages.defaultExpectation.paramPtrs = &ChatServiceMockGetChatMessagesParamPtrs{}
	}
	mmGetChatMessages.defaultExpectation.paramPtrs.chatId = &chatId
	mmGetChatMessages.defaultExpectation.expectationOrigins.originChatId = minimock.CallerInfo(1)

	return mmGetChatMessages
}

// Inspect accepts an inspector function that has same arguments as the ChatService.GetChatMessages
func (mmGetChatMessages *mChatServiceMockGetChatMessages) Inspect(f func(ctx context.Context, chatId int64)) *mChatServiceMockGetChatMessages {
	if mmGetChatMessages.mock.inspectFuncGetChatMessages != nil {
		mmGetChatMessages.mock.t.Fatalf("Inspect function is already set for ChatServiceMock.GetChatMessages")
	}

	mmGetChatMessages.mock.inspectFuncGetChatMessages = f

	return mmGetChatMessages
}

// Return sets up results that will be returned by ChatService.GetChatMessages
func (mmGetChatMessages *mChatServiceMockGetChatMessages) Return(mpa1 []*models.Message, err error) *ChatServiceMock {
	if mmGetChatMessages.mock.funcGetChatMessages != nil {
		mmGetChatMessages.mock.t.Fatalf("ChatServiceMock.GetChatMessages mock is already set by Set")
	}

	if mmGetChatMessages.defaultExpectation == nil {
		mmGetChatMessages.defaultExpectation = &ChatServiceMockGetChatMessagesExpectation{mock: mmGetChatMessages.mock}
	}
	mmGetChatMessages.defaultExpectation.results = &ChatServiceMockGetChatMessagesResults{mpa1, err}
	mmGetChatMessages.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetChatMessages.mock
}

// Set uses given function f to mock the ChatService.GetChatMessages method
func (mmGetChatMessages *mChatServiceMockGetChatMessages) Set(f func(ctx context.Context, chatId int64) (mpa1 []*models.Message, err error)) *ChatServiceMock {
	if mmGetChatMessages.defaultExpectation != nil {
		mmGetChatMessages.mock.t.Fatalf("Default expectation is already set for the ChatService.GetChatMessages method")
	}

	if len(mmGetChatMessages.expectations) > 0 {
		mmGetChatMessages.mock.t.Fatalf("Some expectations are already set for the ChatService.GetChatMessages method")
	}

	mmGetChatMessages.mock.funcGetChatMessages = f
	mmGetChatMessages.mock.funcGetChatMessagesOrigin = minimock.CallerInfo(1)
	return mmGetChatMessages.mock
}

// When sets expectation for the ChatService.GetChatMessages which will trigger the result defined by the following
// Then helper
func (mmGetChatMessages *mChatServiceMockGetChatMessages) When(ctx context.Context, chatId int64) *ChatServiceMockGetChatMessagesExpectation {
	if mmGetChatMessages.mock.funcGetChatMessages != nil {
		mmGetChatMessages.mock.t.Fatalf("ChatServiceMock.GetChatMessages mock is already set by Set")
	}

	expectation := &ChatServiceMockGetChatMessagesExpectation{
		mock:               mmGetChatMessages.mock,
		params:             &ChatServiceMockGetChatMessagesParams{ctx, chatId},
		expectationOrigins: ChatServiceMockGetChatMessagesExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetChatMessages.expectations = append(mmGetChatMessages.expectations, expectation)
	return expectation
}

// Then sets up ChatService.GetChatMessages return parameters for the expectation previously defined by the When method
func (e *ChatServiceMockGetChatMessagesExpectation) Then(mpa1 []*models.Message, err error) *ChatServiceMock {
	e.results = &ChatServiceMockGetChatMessagesResults{mpa1, err}
	return e.mock
}

// Times sets number of times ChatService.GetChatMessages should be invoked
func (mmGetChatMessages *mChatServiceMockGetChatMessages) Times(n uint64) *mChatServiceMockGetChatMessages {
	if n == 0 {
		mmGetChatMessages.mock.t.Fatalf("Times of ChatServiceMock.GetChatMessages mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetChatMessages.expectedInvocations, n)
	mmGetChatMessages.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetChatMessages
}

func (mmGetChatMessages *mChatServiceMockGetChatMessages) invocationsDone() bool {
	if len(mmGetChatMessages.expectations) == 0 && mmGetChatMessages.defaultExpectation == nil && mmGetChatMessages.mock.funcGetChatMessages == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetChatMessages.mock.afterGetChatMessagesCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetChatMessages.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetChatMessages implements mm_servinterface.ChatService
func (mmGetChatMessages *ChatServiceMock) GetChatMessages(ctx context.Context, chatId int64) (mpa1 []*models.Message, err error) {
	mm_atomic.AddUint64(&mmGetChatMessages.beforeGetChatMessagesCounter, 1)
	defer mm_atomic.AddUint64(&mmGetChatMessages.afterGetChatMessagesCounter, 1)

	mmGetChatMessages.t.Helper()

	if mmGetChatMessages.inspectFuncGetChatMessages != nil {
		mmGetChatMessages.inspectFuncGetChatMessages(ctx, chatId)
	}

	mm_params := ChatServiceMockGetChatMessagesParams{ctx, chatId}

	// Record call args
	mmGetChatMessages.GetChatMessagesMock.mutex.Lock()
	mmGetChatMessages.GetChatMessagesMock.callArgs = append(mmGetChatMessages.GetChatMessagesMock.callArgs, &mm_params)
	mmGetChatMessages.GetChatMessagesMock.mutex.Unlock()

	for _, e := range mmGetChatMessages.GetChatMessagesMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.mpa1, e.results.err
		}
	}

	if mmGetChatMessages.GetChatMessagesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetChatMessages.GetChatMessagesMock.defaultExpectation.Counter, 1)
		mm_want := mmGetChatMessages.GetChatMessagesMock.defaultExpectation.params
		mm_want_ptrs := mmGetChatMessages.GetChatMessagesMock.defaultExpectation.paramPtrs

		mm_got := ChatServiceMockGetChatMessagesParams{ctx, chatId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetChatMessages.t.Errorf("ChatServiceMock.GetChatMessages got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetChatMessages.GetChatMessagesMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.chatId != nil && !minimock.Equal(*mm_want_ptrs.chatId, mm_got.chatId) {
				mmGetChatMessages.t.Errorf("ChatServiceMock.GetChatMessages got unexpected parameter chatId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetChatMessages.GetChatMessagesMock.defaultExpectation.expectationOrigins.originChatId, *mm_want_ptrs.chatId, mm_got.chatId, minimock.Diff(*mm_want_ptrs.chatId, mm_got.chatId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetChatMessages.t.Errorf("ChatServiceMock.GetChatMessages got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetChatMessages.GetChatMessagesMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetChatMessages.GetChatMessagesMock.defaultExpectation.results
		if mm_results == nil {
			mmGetChatMessages.t.Fatal("No results are set for the ChatServiceMock.GetChatMessages")
		}
		return (*mm_results).mpa1, (*mm_results).err
	}
	if mmGetChatMessages.funcGetChatMessages != nil {
		return mmGetChatMessages.funcGetChatMessages(ctx, chatId)
	}
	mmGetChatMessages.t.Fatalf("Unexpected call to ChatServiceMock.GetChatMessages. %v %v", ctx, chatId)
	return
}

// GetChatMessagesAfterCounter returns a count of finished ChatServiceMock.GetChatMessages invocations
func (mmGetChatMessages *ChatServiceMock) GetChatMessagesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetChatMessages.afterGetChatMessagesCounter)
}

// GetChatMessagesBeforeCounter returns a count of ChatServiceMock.GetChatMessages invocations
func (mmGetChatMessages *ChatServiceMock) GetChatMessagesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetChatMessages.beforeGetChatMessagesCounter)
}

// Calls returns a list of arguments used in each call to ChatServiceMock.GetChatMessages.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetChatMessages *mChatServiceMockGetChatMessages) Calls() []*ChatServiceMockGetChatMessagesParams {
	mmGetChatMessages.mutex.RLock()

	argCopy := make([]*ChatServiceMockGetChatMessagesParams, len(mmGetChatMessages.callArgs))
	copy(argCopy, mmGetChatMessages.callArgs)

	mmGetChatMessages.mutex.RUnlock()

	return argCopy
}

// MinimockGetChatMessagesDone returns true if the count of the GetChatMessages invocations corresponds
// the number of defined expectations
func (m *ChatServiceMock) MinimockGetChatMessagesDone() bool {
	if m.GetChatMessagesMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetChatMessagesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetChatMessagesMock.invocationsDone()
}

// MinimockGetChatMessagesInspect logs each unmet expectation
func (m *ChatServiceMock) MinimockGetChatMessagesInspect() {
	for _, e := range m.GetChatMessagesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ChatServiceMock.GetChatMessages at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetChatMessagesCounter := mm_atomic.LoadUint64(&m.afterGetChatMessagesCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetChatMessagesMock.defaultExpectation != nil && afterGetChatMessagesCounter < 1 {
		if m.GetChatMessagesMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ChatServiceMock.GetChatMessages at\n%s", m.GetChatMessagesMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ChatServiceMock.GetChatMessages at\n%s with params: %#v", m.GetChatMessagesMock.defaultExpectation.expectationOrigins.origin, *m.GetChatMessagesMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetChatMessages != nil && afterGetChatMessagesCounter < 1 {
		m.t.Errorf("Expected call to ChatServiceMock.GetChatMessages at\n%s", m.funcGetChatMessagesOrigin)
	}

	if !m.GetChatMessagesMock.invocationsDone() && afterGetChatMessagesCounter > 0 {
		m.t.Errorf("Expected %d calls to ChatServiceMock.GetChatMessages at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetChatMessagesMock.expectedInvocations), m.GetChatMessagesMock.expectedInvocationsOrigin, afterGetChatMessagesCounter)
	}
}

type mChatServiceMockSendMessage struct {
	optional           bool
	mock               *ChatServiceMock
	defaultExpectation *ChatServiceMockSendMessageExpectation
	expectations       []*ChatServiceMockSendMessageExpectation

	callArgs []*ChatServiceMockSendMessageParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ChatServiceMockSendMessageExpectation specifies expectation struct of the ChatService.SendMessage
type ChatServiceMockSendMessageExpectation struct {
	mock               *ChatServiceMock
	params             *ChatServiceMockSendMessageParams
	paramPtrs          *ChatServiceMockSendMessageParamPtrs
	expectationOrigins ChatServiceMockSendMessageExpectationOrigins
	results            *ChatServiceMockSendMessageResults
	returnOrigin       string
	Counter            uint64
}

// ChatServiceMockSendMessageParams contains parameters of the ChatService.SendMessage
type ChatServiceMockSendMessageParams struct {
	ctx     context.Context
	message *models.Message
}

// ChatServiceMockSendMessageParamPtrs contains pointers to parameters of the ChatService.SendMessage
type ChatServiceMockSendMessageParamPtrs struct {
	ctx     *context.Context
	message **models.Message
}

// ChatServiceMockSendMessageResults contains results of the ChatService.SendMessage
type ChatServiceMockSendMessageResults struct {
	mp1 *models.Message
	err error
}

// ChatServiceMockSendMessageOrigins contains origins of expectations of the ChatService.SendMessage
type ChatServiceMockSendMessageExpectationOrigins struct {
	origin        string
	originCtx     string
	originMessage string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendMessage *mChatServiceMockSendMessage) Optional() *mChatServiceMockSendMessage {
	mmSendMessage.optional = true
	return mmSendMessage
}

// Expect sets up expected params for ChatService.SendMessage
func (mmSendMessage *mChatServiceMockSendMessage) Expect(ctx context.Context, message *models.Message) *mChatServiceMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("ChatServiceMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &ChatServiceMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.paramPtrs != nil {
		mmSendMessage.mock.t.Fatalf("ChatServiceMock.SendMessage mock is already set by ExpectParams functions")
	}

	mmSendMessage.defaultExpectation.params = &ChatServiceMockSendMessageParams{ctx, message}
	mmSendMessage.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendMessage.expectations {
		if minimock.Equal(e.params, mmSendMessage.defaultExpectation.params) {
			mmSendMessage.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendMessage.defaultExpectation.params)
		}
	}

	return mmSendMessage
}

// ExpectCtxParam1 sets up expected param ctx for ChatService.SendMessage
func (mmSendMessage *mChatServiceMockSendMessage) ExpectCtxParam1(ctx context.Context) *mChatServiceMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("ChatServiceMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &ChatServiceMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.params != nil {
		mmSendMessage.mock.t.Fatalf("ChatServiceMock.SendMessage mock is already set by Expect")
	}

	if mmSendMessage.defaultExpectation.paramPtrs == nil {
		mmSendMessage.defaultExpectation.paramPtrs = &ChatServiceMockSendMessageParamPtrs{}
	}
	mmSendMessage.defaultExpectation.paramPtrs.ctx = &ctx
	mmSendMessage.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSendMessage
}

// ExpectMessageParam2 sets up expected param message for ChatService.SendMessage
func (mmSendMessage *mChatServiceMockSendMessage) ExpectMessageParam2(message *models.Message) *mChatServiceMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("ChatServiceMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &ChatServiceMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.params != nil {
		mmSendMessage.mock.t.Fatalf("ChatServiceMock.SendMessage mock is already set by Expect")
	}

	if mmSendMessage.defaultExpectation.paramPtrs == nil {
		mmSendMessage.defaultExpectation.paramPtrs = &ChatServiceMockSendMessageParamPtrs{}
	}
	mmSendMessage.defaultExpectation.paramPtrs.message = &message
	mmSendMessage.defaultExpectation.expectationOrigins.originMessage = minimock.CallerInfo(1)

	return mmSendMessage
}

// Inspect accepts an inspector function that has same arguments as the ChatService.SendMessage
func (mmSendMessage *mChatServiceMockSendMessage) Inspect(f func(ctx context.Context, message *models.Message)) *mChatServiceMockSendMessage {
	if mmSendMessage.mock.inspectFuncSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("Inspect function is already set for ChatServiceMock.SendMessage")
	}

	mmSendMessage.mock.inspectFuncSendMessage = f

	return mmSendMessage
}

// Return sets up results that will be returned by ChatService.SendMessage
func (mmSendMessage *mChatServiceMockSendMessage) Return(mp1 *models.Message, err error) *ChatServiceMock {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("ChatServiceMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &ChatServiceMockSendMessageExpectation{mock: mmSendMessage.mock}
	}
	mmSendMessage.defaultExpectation.results = &ChatServiceMockSendMessageResults{mp1, err}
	mmSendMessage.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendMessage.mock
}

// Set uses given function f to mock the ChatService.SendMessage method
func (mmSendMessage *mChatServiceMockSendMessage) Set(f func(ctx context.Context, message *models.Message) (mp1 *models.Message, err error)) *ChatServiceMock {
	if mmSendMessage.defaultExpectation != nil {
		mmSendMessage.mock.t.Fatalf("Default expectation is already set for the ChatService.SendMessage method")
	}

	if len(mmSendMessage.expectations) > 0 {
		mmSendMessage.mock.t.Fatalf("Some expectations are already set for the ChatService.SendMessage method")
	}

	mmSendMessage.mock.funcSendMessage = f
	mmSendMessage.mock.funcSendMessageOrigin = minimock.CallerInfo(1)
	return mmSendMessage.mock
}

// When sets expectation for the ChatService.SendMessage which will trigger the result defined by the following
// Then helper
func (mmSendMessage *mChatServiceMockSendMessage) When(ctx context.Context, message *models.Message) *ChatServiceMockSendMessageExpectation {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("ChatServiceMock.SendMessage mock is already set by Set")
	}

	expectation := &ChatServiceMockSendMessageExpectation{
		mock:               mmSendMessage.mock,
		params:             &ChatServiceMockSendMessageParams{ctx, message},
		expectationOrigins: ChatServiceMockSendMessageExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendMessage.expectations = append(mmSendMessage.expectations, expectation)
	return expectation
}

// Then sets up ChatService.SendMessage return parameters for the expectation previously defined by the When method
func (e *ChatServiceMockSendMessageExpectation) Then(mp1 *models.Message, err error) *ChatServiceMock {
	e.results = &ChatServiceMockSendMessageResults{mp1, err}
	return e.mock
}

// Times sets number of times ChatService.SendMessage should be invoked
func (mmSendMessage *mChatServiceMockSendMessage) Times(n uint64) *mChatServiceMockSendMessage {
	if n == 0 {
		mmSendMessage.mock.t.Fatalf("Times of ChatServiceMock.SendMessage mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendMessage.expectedInvocations, n)
	mmSendMessage.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendMessage
}

func (mmSendMessage *mChatServiceMockSendMessage) invocationsDone() bool {
	if len(mmSendMessage.expectations) == 0 && mmSendMessage.defaultExpectation == nil && mmSendMessage.mock.funcSendMessage == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendMessage.mock.afterSendMessageCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendMessage.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendMessage implements mm_servinterface.ChatService
func (mmSendMessage *ChatServiceMock) SendMessage(ctx context.Context, message *models.Message) (mp1 *models.Message, err error) {
	mm_atomic.AddUint64(&mmSendMessage.beforeSendMessageCounter, 1)
	defer mm_atomic.AddUint64(&mmSendMessage.afterSendMessageCounter, 1)

	mmSendMessage.t.Helper()

	if mmSendMessage.inspectFuncSendMessage != nil {
		mmSendMessage.inspectFuncSendMessage(ctx, message)
	}

	mm_params := ChatServiceMockSendMessageParams{ctx, message}

	// Record call args
	mmSendMessage.SendMessageMock.mutex.Lock()
	mmSendMessage.SendMessageMock.callArgs = append(mmSendMessage.SendMessageMock.callArgs, &mm_params)
	mmSendMessage.SendMessageMock.mutex.Unlock()

	for _, e := range mmSendMessage.SendMessageMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.mp1, e.results.err
		}
	}

	if mmSendMessage.SendMessageMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendMessage.SendMessageMock.defaultExpectation.Counter, 1)
		mm_want := mmSendMessage.SendMessageMock.defaultExpectation.params
		mm_want_ptrs := mmSendMessage.SendMessageMock.defaultExpectation.paramPtrs

		mm_got := ChatServiceMockSendMessageParams{ctx, message}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSendMessage.t.Errorf("ChatServiceMock.SendMessage got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.message != nil && !minimock.Equal(*mm_want_ptrs.message, mm_got.message) {
				mmSendMessage.t.Errorf("ChatServiceMock.SendMessage got unexpected parameter message, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.originMessage, *mm_want_ptrs.message, mm_got.message, minimock.Diff(*mm_want_ptrs.message, mm_got.message))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendMessage.t.Errorf("ChatServiceMock.SendMessage got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendMessage.SendMessageMock.defaultExpectation.results
		if mm_results == nil {
			mmSendMessage.t.Fatal("No results are set for the ChatServiceMock.SendMessage")
		}
		return (*mm_results).mp1, (*mm_results).err
	}
	if mmSendMessage.funcSendMessage != nil {
		return mmSendMessage.funcSendMessage(ctx, message)
	}
	mmSendMessage.t.Fatalf("Unexpected call to ChatServiceMock.SendMessage. %v %v", ctx, message)
	return
}

// SendMessageAfterCounter returns a count of finished ChatServiceMock.SendMessage invocations
func (mmSendMessage *ChatServiceMock) SendMessageAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendMessage.afterSendMessageCounter)
}

// SendMessageBeforeCounter returns a count of ChatServiceMock.SendMessage invocations
func (mmSendMessage *ChatServiceMock) SendMessageBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendMessage.beforeSendMessageCounter)
}

// Calls returns a list of arguments used in each call to ChatServiceMock.SendMessage.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendMessage *mChatServiceMockSendMessage) Calls() []*ChatServiceMockSendMessageParams {
	mmSendMessage.mutex.RLock()

	argCopy := make([]*ChatServiceMockSendMessageParams, len(mmSendMessage.callArgs))
	copy(argCopy, mmSendMessage.callArgs)

	mmSendMessage.mutex.RUnlock()

	return argCopy
}

// MinimockSendMessageDone returns true if the count of the SendMessage invocations corresponds
// the number of defined expectations
func (m *ChatServiceMock) MinimockSendMessageDone() bool {
	if m.SendMessageMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendMessageMock.invocationsDone()
}

// MinimockSendMessageInspect logs each unmet expectation
func (m *ChatServiceMock) MinimockSendMessageInspect() {
	for _, e := range m.SendMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ChatServiceMock.SendMessage at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendMessageCounter := mm_atomic.LoadUint64(&m.afterSendMessageCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendMessageMock.defaultExpectation != nil && afterSendMessageCounter < 1 {
		if m.SendMessageMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ChatServiceMock.SendMessage at\n%s", m.SendMessageMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ChatServiceMock.SendMessage at\n%s with params: %#v", m.SendMessageMock.defaultExpectation.expectationOrigins.origin, *m.SendMessageMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendMessage != nil && afterSendMessageCounter < 1 {
		m.t.Errorf("Expected call to ChatServiceMock.SendMessage at\n%s", m.funcSendMessageOrigin)
	}

	if !m.SendMessageMock.invocationsDone() && afterSendMessageCounter > 0 {
		m.t.Errorf("Expected %d calls to ChatServiceMock.SendMessage at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendMessageMock.expectedInvocations), m.SendMessageMock.expectedInvocationsOrigin, afterSendMessageCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ChatServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddMemberToChatInspect()

			m.MinimockCreateChatInspect()

			m.MinimockGetChatByIdInspect()

			m.MinimockGetChatMessagesInspect()

			m.MinimockSendMessageInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ChatServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ChatServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddMemberToChatDone() &&
		m.MinimockCreateChatDone() &&
		m.MinimockGetChatByIdDone() &&
		m.MinimockGetChatMessagesDone() &&
		m.MinimockSendMessageDone()
}
